remote_theme: DigitaleGesellschaft/jekyll-theme-conference@v3.6.3
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

title: Your Conference 2025
description: "Annual conference on [topic]"
url: "https://[your-username].github.io"

# Conference specific settings
conference:
  name: Your Conference Name
  description: Conference Description
  date: June 15-17, 2025
  location: City, Country
  venue: Convention Center Name
  
# Navigation
navigation_links:
  - name: Program
    relative_url: /program/
  - name: Speakers
    relative_url: /speakers/
  - name: Venue
    relative_url: /location/
  - name: Registration
    absolute_url: "https://registration-link.com"
    disabled: false
